apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-api
  namespace: done-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      containers:
        - name: tasks-api
          image: localhost:5000/tasks-api:1
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: tasks-api-secrets
                  key: connection-string
          ports:
            - containerPort: 4000