apiVersion: v1
kind: Secret
metadata:
  name: collections-api-secrets
  namespace: done-api
type: Opaque
data:
  DB_URL: <tu-secreto-en-base64-aquí> # MongoDB
  DB_NAME: ZG9uZQo= # = done
  REDIS_URL: <tu-secreto-en-base64-aquí> # Redis