apiVersion: v1
kind: Service
metadata:
  name: collections-api-svc
  namespace: done-api
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: collections-api